### ISSUE TITLE
Exceptions from method call not resolved

### ISSUE THREAD

**Issue by Wulfheart** [dedoc/scramble#194] opened 2023-08-22 10:27 UTC
Given the following Controller
```php
final class SomeController extends Controller
{
    public function __invoke(): void
    {
        $s = new SomeService();
        $s->notFound();
    }
}
```

and the following service
```php
final class SomeService
{
    /**
     * @throws BasketException
     */
    public function throw(): void
    {
        throw new BasketException();
    }

    /**
     * @throws NotFoundHttpException
     */
    public function notFound(): void
    {
        throw new NotFoundHttpException();
    }
}
```

I would expect the the OpenAPI schema to recognize that it can be a 404 response. However, it does not get shown in the docs.
![image](https://github.com/dedoc/scramble/assets/25671390/c4620a34-2cfd-4b35-8b3a-9103db3f2fca)

Note: I would have written a fix for this myself but I am unable to access classes which are not a controller class via the `$scope` variable.

**Comment by romalytvynenko** [comment] 2023-08-24 07:43
Hey @Wulfheart! This is an intended behavior, at least for now.

The reason why exceptions are not resolved deeply is performance cost for this. I was able to make Scramble faster due to making sure it deeply analyzes only the code that is taking part into what is returned by the method. This allows Scramble to avoid analyzing other method calls, which makes it faster.

In case of deeply analyzing exceptions, Scramble will need to analyze all method calls, even those that are not affecting returned value in some way. It will make Scramble slow, so I've decided that it is good trade-off. 

So as a workaround, you can annotate the exception in your controller:
```php
final class SomeController extends Controller
{
    /**
     * @throws NotFoundHttpException
     */
    public function __invoke(): void
    {
        $s = new SomeService();
        $s->notFound();
    }
}
```

**Comment by Wulfheart** [comment] 2023-08-24 08:49
Thanks for your response @romalytvynenko. Might something like a generator then be more viable? Would be cheaper on server resources in prod anyways...

**Comment by rvzug** [comment] 2023-08-24 17:42
Maybe related, some of my controllers are calling ``new \Exception($message)`` the Class-(and/or Method)Reflector can't handle this class, resulting in a file_get_contents(null);

**Comment by romalytvynenko** [comment] 2023-08-25 06:08
@rvzug Can you please elaborate? Share some code examples, etc. 'cause I don't understand what is going on there

**Comment by romalytvynenko** [comment] 2023-08-26 12:57
@Wulfheart 

> Might something like a generator then be more viable?

Generators help reduce memory usage, but the time spent on some work is still there. So I don't see generators will help with the time of docs generation, which is the primary motivation here.

@rvzug please feel free to create an issue for your problem with more details.

Will close this issue, but I will keep it in mind.

**Closed by romalytvynenko** 2023-08-26 12:57 UTC

**Comment by Wulfheart** [comment] 2023-08-26 14:12
Yes, it might still take some time to get updated but on subsequent calls it will already be available. Furthermore it could make use of internal caching…

**Comment by romalytvynenko** [comment] 2023-08-26 14:38
My approach to Scramble's performance is to make sure that the very first docs generation is fast. So if something affects first docs generation time, I'm more inclined not to include it.

**Comment by Wulfheart** [comment] 2023-08-26 15:09
This is good for dev mode in my opinion but why should it be fast in production? You can just run a generator before every deployment and there you go.

**Comment by romalytvynenko** [comment] 2023-08-26 15:12
That's exactly what I'm trying to have here: a great DX which means it should be fast in dev mode :)

**Comment by Wulfheart** [comment] 2023-08-26 18:21
I personally believe that a little delay (which isn’t so slow - PHPStan is quite fast) is acceptable for a more thorough feature set. With a caching strategy the data for each file the generation will be as fast as the current approach or even faster. But at the end of the day it is your project, I just want to provide another perspective. I don’t have the resources right now to implement such changes unfortunately. I am sure that whatever decision you are going to make it will be the correct one for this project. ☺️
